### ISSUE TITLE
Where is Taiwan?

### ISSUE THREAD

**Issue by elgs** [ecomfe/echarts-x#2]
I think you guys mixed Taiwan and China.

**Comment by leeight** [comment]
Maybe it's an "issue", but won't fix?

**Comment by elgs** [comment]
I don't think they dare to fix it.

**Comment by chriswong** [comment]
No, it's a feature.

> Maybe it's an "issue", but won't fix?

**Comment by elgs** [comment]
It's difficult to understand the way Chinese think.

**Comment by Justineo** [comment]
I think concerns about geo data shouldn't be an issue for this repo, as long as it can take configurable data. Every country has similar controversial issues and you cannot satisfy everyone. It's not so difficult to understand that actually.

**Comment by leeight** [comment]
都能看懂汉字，整啥英文呀

**Comment by elgs** [comment]
@Justineo agreed. Making it configurable should definitely make more sense for Taiwan people, and showing respect to them.

**Comment by 599316527** [comment]
The most political correctness strategy which Apple or Google are applying is loading different geographic data for people from various countries to satisfy everyone. 
But talking about it here is pointless, isn't it?

**Comment by HuaTiMeiTian** [comment]
台灣人有權利在地圖上把兩邊分開，我們也有權利放在一塊，這是哪邊的產品具體內容就由哪邊決定，互不干涉
