### ISSUE TITLE
分片加载底图

### ISSUE THREAD

**Issue by ChiChou** [ecomfe/echarts-x#3]
目前底图纹理用的单张 jpg，放大之后锯齿挺重的。

有打算改用兼容 leaflet 底图源，根据旋转角度和放大级别来加载纹理吗？

下面两个引擎都支持：

* [cesium](https://github.com/AnalyticalGraphicsInc/cesium/)
* [webglearth2](https://github.com/webglearth/webglearth2)

P.S.

这个项目太赞了，实现了很多以前本菜想做做不出来的效果……

**Comment by pissang** [comment]
暂时不会考虑，因为定位不一样，cesium是有GIS API提供数据的，ECharts 有一条原则就是不继承数据获取接口，ECharts-X也是一样。当然不排除以后会通过插件的形式实现，就像现在ECharts的百度地图插件一样，不过我们得好好考虑如何提供便捷的方式实现 LOD。

最后谢谢建议:) 现在还只有0.1版本，改进的空间还很大。
