### ISSUE TITLE
Cross-domain textures

### ISSUE THREAD

**Issue by jarben** [ecomfe/echarts-x#6]
I was playing with EChartsX over the weekend and found one challenge, I'm rendering ECharts in a sandboxed iframe with "allow-same-origin" policy disabled at the moment. This basically means that all images (including those from the same domain) are considered as cross-domain. 

The issue is that I can't use ECharts layers at the moment as it throws: 
SecurityError: Failed to execute 'texImage2D' on 'WebGLRenderingContext': Tainted canvases may not be loaded.

So my humble question is if there is any way to enable cross domain resources in WebGL. As far as I know, using cross-domain images in 2D canvas is possible by doing something like this: 
image.crossOrigin = "anonymous";

WebGL spec does mention the same approach but I'm not sure if it's applicable or not: 
https://www.khronos.org/registry/webgl/specs/latest/1.0/#4.2

Would it be possible to have an option for cross-domain layers and add .crossOrigin = "anonymous"; when enabled? 

My other option is to register a new domain name for my sandbox which would prevent security issues even if allow-same-origin was enabled so I have a workaround:) 

Anyway, EChartsX look really impressive so can't wait to see more samples;)

Cheers, 
Jaro

**Comment by pissang** [comment]
Currently it is possible to create a CORS image and use it as a value instead of a simple image url. And as I know, using a CORS image also need the server to be configured to support cross domain access.

Thanks for the feedback. Maybe we need to add a CORS option to make it more convenient :)
