### ISSUE TITLE
按照官网上的引入方式没有出图。

### ISSUE THREAD

**Issue by Seven0711** [ecomfe/echarts-x#7]
require([
            'echarts',
            'echarts-x',
            // ECharts-X 中 map3d 的地图绘制基于 ECharts 中的 map。
            'echarts/chart/map',
            'echarts/chart/map3d'
........
这是官网给的.但是没用,最后一行改成"  'echarts-x/chart/map3d' "才有效果。

**Comment by pissang** [comment]
哦对这里是文档错误，抱歉
