### ISSUE TITLE
Map3D 支持addMarkPoint么？

### ISSUE THREAD

**Issue by zicai** [ecomfe/echarts-x#8]
myChart.setOption({
            series: [{
              name: 'World Population',
              type: 'map3d',
              mapType: 'world',
              markPoint: {
                data: [{distance:0,geoCoord:[0,0],symbolSize:0}]
              }
            }]
          });
          myChart.addMarkPoint(0,{
            data:PopulationData
          });

echarts.js 中代码：
`chart && chart.addMark(seriesIdx, markData, markType);`
报错：
`Uncaught TypeError: undefined is not a function`

**Comment by pissang** [comment]
目前还不支持

**Comment by zicai** [comment]
thanks

**Comment by lmxhappy** [comment]
不支持的话，那如果想改变markpoint或者markline的颜色，怎么办呢？像例子里面的使用ajax吗？

**Comment by pissang** [comment]
通过 setOption 的方式，在数据量比较大的时候 Map3D 中的点都是批量创建的。所以 addMarkPoint 和 setOption 两个差别不大

**Comment by lmxhappy** [comment]
通过ajax从后台获取markPoint或者markLine的状态（或颜色），然后调用setOption设置？另外，我在echarts调用addMarkPoint是没有问题的，在echarts-x下却报错——“Uncaught TypeError: c.delMark is not a function”，是因为echarts-x不支持addMarkPoint吗？

**Comment by pissang** [comment]
嗯，不支持

**Comment by lmxhappy** [comment]
建议添加此类函数，以保持与echarts一致，方便用户将其地图从2d迁移到3d。谢谢

**Comment by pissang** [comment]
谢谢建议
