### ISSUE TITLE
和echarts冲突问题

### ISSUE THREAD

**Issue by pipistreking** [ecomfe/echarts-x#9]
map3d 和 map2D 混合使用时，2d地图上的markpoint 炫光效果的颜色失效（全部是黑色）symbol:'emptyCircle'，

比如 map3d_mix.html demo界面，给2d中国地图上添加标注 markpoint ，使用 dataRange并启用漫游，markpoint 的炫光效果，颜色失效。

在同一个页面，单独初始化3D和2Dmap也解决不了。

markpoint 的effect 增加 color 属性可以解决问题，但是颜色只能使用单色。并且不会随dataRange的颜色变化。

PS:markpoint 的颜色优先级应该是：datarange < markpoint(itemStyle:color) < effect(color)

**Comment by pissang** [comment]
ECharts 中 markPoint 启用 large 后因为优化的需要是不支持通过 dataRange 使用多种颜色的。
